
language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=author.settings

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

script:
  - python manage.py test
